version: '3.4'

services:

  mongodb:
    image: mongo
    container_name: "mongodb"
    restart: always
    ports:
        - 27017:27017
    networks:
      - databases
    volumes:
      - ./_databases/mongodb/mongo-data:/data/posts
    command: mongod

  server:
    build:
      context: ./server
    container_name: "server"
    volumes:
      - ./server:/usr/src/server
      - /usr/src/server/node_modules
    depends_on:
      - mongodb
    ports: 
      - "5000:5000"
    environment:
      WAIT+HOSTS: mongodb:27017
    networks:
      - server
      - databases

  client:
    build: 
      context: ./client
    container_name: "client"
    volumes:
      - ./client:/usr/src/client
      - /usr/src/client/node_modules
    ports:
      - "8080:8080"
    networks:
      - server


networks:
  server:
  databases: